-- Timeline Application Database Schema
-- PostgreSQL 17
-- Generated: 2026-04-12

-- ============================================================
-- TABLES
-- ============================================================

-- 스쿼드
CREATE TABLE squad (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description character varying(500),
    color character varying(7),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT squad_pkey PRIMARY KEY (id),
    CONSTRAINT squad_name_unique UNIQUE (name)
);

-- 공휴일
CREATE TABLE holiday (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT holiday_pkey PRIMARY KEY (id),
    CONSTRAINT holiday_type_check CHECK (type IN ('NATIONAL', 'COMPANY'))
);

-- 멤버
CREATE TABLE member (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    email character varying(200),
    role character varying(20) NOT NULL,
    team character varying(100),
    capacity numeric(3,1) NOT NULL,
    active boolean NOT NULL,
    queue_start_date date,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT member_pkey PRIMARY KEY (id),
    CONSTRAINT member_role_check CHECK (role IN ('BE', 'FE', 'QA', 'PM', 'EM', 'PD'))
);

-- 멤버 휴무
CREATE TABLE member_leave (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL,
    date date NOT NULL,
    reason character varying(200),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT member_leave_pkey PRIMARY KEY (id),
    CONSTRAINT fk_member_leave_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 프로젝트
CREATE TABLE project (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description text,
    jira_board_id character varying(100),
    jira_epic_key character varying(100),
    total_man_days_override numeric(10,1),
    quarter character varying(200),
    status character varying(20),
    ktlo boolean NOT NULL DEFAULT false,
    sort_order integer,
    ppl_id bigint,
    epl_id bigint,
    start_date date,
    end_date date,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT project_status_check CHECK (status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD')),
    CONSTRAINT fk_project_ppl FOREIGN KEY (ppl_id) REFERENCES member(id),
    CONSTRAINT fk_project_epl FOREIGN KEY (epl_id) REFERENCES member(id)
);

-- 프로젝트 마일스톤
CREATE TABLE project_milestone (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    type character varying(20),
    start_date date,
    end_date date,
    days integer,
    qa_assignees character varying(500),
    sort_order integer,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_milestone_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_milestone_project FOREIGN KEY (project_id) REFERENCES project(id)
);

-- 스쿼드 멤버
CREATE TABLE squad_member (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    squad_id bigint NOT NULL,
    member_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT squad_member_pkey PRIMARY KEY (id),
    CONSTRAINT squad_member_unique UNIQUE (squad_id, member_id),
    CONSTRAINT fk_squad_member_squad FOREIGN KEY (squad_id) REFERENCES squad(id),
    CONSTRAINT fk_squad_member_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 프로젝트 멤버
CREATE TABLE project_member (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    member_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_member_pkey PRIMARY KEY (id),
    CONSTRAINT project_member_unique UNIQUE (project_id, member_id),
    CONSTRAINT fk_project_member_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_project_member_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 프로젝트 스쿼드
CREATE TABLE project_squad (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    squad_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_squad_pkey PRIMARY KEY (id),
    CONSTRAINT project_squad_unique UNIQUE (project_id, squad_id),
    CONSTRAINT fk_pds_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_pds_squad FOREIGN KEY (squad_id) REFERENCES squad(id)
);

-- 태스크
CREATE TABLE task (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    squad_id bigint,
    assignee_id bigint,
    name character varying(300) NOT NULL,
    description text,
    status character varying(20) NOT NULL,
    priority character varying(5),
    type character varying(20),
    execution_mode character varying(20) NOT NULL DEFAULT 'SEQUENTIAL',
    man_days numeric(5,1),
    start_date date,
    end_date date,
    actual_end_date date,
    jira_key character varying(50),
    sort_order integer,
    assignee_order integer,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT task_status_check CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'DONE', 'HOLD', 'CANCELLED')),
    CONSTRAINT task_priority_check CHECK (priority IN ('P0', 'P1', 'P2', 'P3')),
    CONSTRAINT task_type_check CHECK (type IN ('FEATURE', 'DESIGN', 'BACKEND', 'INFRA', 'QA', 'RELEASE', 'OPS', 'TECH_DEBT')),
    CONSTRAINT task_execution_mode_check CHECK (execution_mode IN ('SEQUENTIAL', 'PARALLEL')),
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_task_squad FOREIGN KEY (squad_id) REFERENCES squad(id),
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES member(id)
);

-- 태스크 의존성
CREATE TABLE task_dependency (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    depends_on_task_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT task_dependency_pkey PRIMARY KEY (id),
    CONSTRAINT task_dependency_unique UNIQUE (task_id, depends_on_task_id),
    CONSTRAINT fk_task_dependency_task FOREIGN KEY (task_id) REFERENCES task(id),
    CONSTRAINT fk_task_dependency_depends_on FOREIGN KEY (depends_on_task_id) REFERENCES task(id)
);

-- 태스크 링크
CREATE TABLE task_link (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    url character varying(2000) NOT NULL,
    label character varying(200) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT task_link_pkey PRIMARY KEY (id),
    CONSTRAINT fk_task_link_task FOREIGN KEY (task_id) REFERENCES task(id)
);

-- 프로젝트 링크
CREATE TABLE project_link (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    url character varying(2000) NOT NULL,
    label character varying(200) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_link_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_link_project FOREIGN KEY (project_id) REFERENCES project(id)
);

-- 프로젝트 메모
CREATE TABLE project_note (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT project_note_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_note_project FOREIGN KEY (project_id) REFERENCES project(id)
);

-- Google Drive OAuth2 연동 설정 (전역 단일 레코드)
CREATE TABLE google_drive_config (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    client_id character varying(500),
    client_secret character varying(500),
    refresh_token text,
    folder_id character varying(200),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT google_drive_config_pkey PRIMARY KEY (id)
);

-- 사이드바 링크
CREATE TABLE sidebar_link (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    label character varying(200) NOT NULL,
    url character varying(2000) NOT NULL,
    icon character varying(50),
    sort_order integer,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT sidebar_link_pkey PRIMARY KEY (id)
);

-- 사이드바 메모
CREATE TABLE sidebar_memo (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content text NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT sidebar_memo_pkey PRIMARY KEY (id)
);

-- Jira 연동 설정 (전역 단일 레코드)
CREATE TABLE jira_config (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    base_url character varying(500),
    email character varying(200),
    api_token character varying(500),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT jira_config_pkey PRIMARY KEY (id)
);
