-- Timeline Application Database Schema
-- PostgreSQL 17
-- Generated: 2026-04-11

-- ============================================================
-- TABLES
-- ============================================================

-- 도메인 시스템
CREATE TABLE domain_system (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description character varying(500),
    color character varying(7),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT domain_system_pkey PRIMARY KEY (id),
    CONSTRAINT domain_system_name_unique UNIQUE (name)
);

-- 공휴일
CREATE TABLE holiday (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT holiday_pkey PRIMARY KEY (id),
    CONSTRAINT holiday_type_check CHECK (type IN ('NATIONAL', 'COMPANY'))
);

-- 멤버
CREATE TABLE member (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    email character varying(200),
    role character varying(20) NOT NULL,
    capacity numeric(3,1) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT member_pkey PRIMARY KEY (id),
    CONSTRAINT member_role_check CHECK (role IN ('ENGINEER', 'QA', 'PM'))
);

-- 멤버 휴무
CREATE TABLE member_leave (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL,
    date date NOT NULL,
    reason character varying(200),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT member_leave_pkey PRIMARY KEY (id),
    CONSTRAINT fk_member_leave_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 프로젝트
CREATE TABLE project (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description text,
    project_type character varying(100),
    status character varying(20),
    start_date date,
    end_date date,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT project_status_check CHECK (status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD'))
);

-- 프로젝트 멤버
CREATE TABLE project_member (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    member_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_member_pkey PRIMARY KEY (id),
    CONSTRAINT project_member_unique UNIQUE (project_id, member_id),
    CONSTRAINT fk_project_member_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_project_member_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 프로젝트 도메인 시스템
CREATE TABLE project_domain_system (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    domain_system_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT project_domain_system_pkey PRIMARY KEY (id),
    CONSTRAINT project_domain_system_unique UNIQUE (project_id, domain_system_id),
    CONSTRAINT fk_pds_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_pds_domain_system FOREIGN KEY (domain_system_id) REFERENCES domain_system(id)
);

-- 태스크
CREATE TABLE task (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    domain_system_id bigint NOT NULL,
    assignee_id bigint,
    name character varying(300) NOT NULL,
    description text,
    status character varying(20) NOT NULL,
    priority character varying(5),
    type character varying(20),
    execution_mode character varying(20) NOT NULL DEFAULT 'SEQUENTIAL',
    man_days numeric(5,1),
    start_date date NOT NULL,
    end_date date NOT NULL,
    actual_end_date date,
    sort_order integer,
    assignee_order integer,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT task_status_check CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'DONE', 'HOLD', 'CANCELLED')),
    CONSTRAINT task_priority_check CHECK (priority IN ('P0', 'P1', 'P2', 'P3')),
    CONSTRAINT task_type_check CHECK (type IN ('FEATURE', 'DESIGN', 'BACKEND', 'INFRA', 'QA', 'RELEASE', 'OPS', 'TECH_DEBT')),
    CONSTRAINT task_execution_mode_check CHECK (execution_mode IN ('SEQUENTIAL', 'PARALLEL')),
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_task_domain_system FOREIGN KEY (domain_system_id) REFERENCES domain_system(id),
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES member(id)
);

-- 태스크 의존성
CREATE TABLE task_dependency (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    depends_on_task_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT task_dependency_pkey PRIMARY KEY (id),
    CONSTRAINT task_dependency_unique UNIQUE (task_id, depends_on_task_id),
    CONSTRAINT fk_task_dependency_task FOREIGN KEY (task_id) REFERENCES task(id),
    CONSTRAINT fk_task_dependency_depends_on FOREIGN KEY (depends_on_task_id) REFERENCES task(id)
);

-- 태스크 링크
CREATE TABLE task_link (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    url character varying(2000) NOT NULL,
    label character varying(200) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT task_link_pkey PRIMARY KEY (id),
    CONSTRAINT fk_task_link_task FOREIGN KEY (task_id) REFERENCES task(id)
);
